### ISSUE TITLE
Discord not recognizing any bot commands

### ISSUE THREAD

**Issue by benndak** [coolbrett/espn-fantasy-basketball-discord-bot#18]
![image](https://github.com/coolbrett/espn-fantasy-basketball-discord-bot/assets/149605958/a2c87d54-8e42-4c22-81c9-1b3f91e007b7)

**Comment by benndak** [comment]
Looks like the commands are now properly recognized, although the bot is offline.

**Comment by coolbrett** [comment]
@benndak I don't have the bot deployed yet so it just runs when I have my PC on for now. Let me know if you run into any other issues
